In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from io import StringIO

常見補值方式有補固定值、平均值、眾數、中位數。
較進階的補值方法有最近差補法（在資料中找與缺失樣本最接近的樣本來補足缺失的特徵）
回歸方法(對帶有缺失的特徵根據其他的特徵屬性來建立回歸模型補值)，或是用插值法（拉格朗日插值法）

In [2]:
data = '''A,B,C,D,E
        5.0,2.0,3.0,,6
        1.0,6.0,,8.0,5.0
        0.0,11.0,12.0,4.0,5.0
        3.0,,3.0,5.0,
        5.0,1.0,4.0,2.0,4
        '''

In [3]:
df = pd.read_csv(StringIO(data))
df

     A     B     C    D    E
0  5.0   2.0   3.0  NaN  6.0
1  1.0   6.0   NaN  8.0  5.0
2  0.0  11.0  12.0  4.0  5.0
3  3.0   NaN   3.0  5.0  NaN
4  5.0   1.0   4.0  2.0  4.0

使用Pandas去空值的方法“dropna”，
dropna預設只要任一欄位有空值，就會整筆刪掉。
可透過參數來調整，像是把how設為all，就是要全部為空才清掉，
或是用subset指定當某一欄為空時才刪。

In [4]:
df.dropna()

     A     B     C    D    E
2  0.0  11.0  12.0  4.0  5.0
4  5.0   1.0   4.0  2.0  4.0

In [5]:
df.dropna(how ='all')

     A     B     C    D    E
0  5.0   2.0   3.0  NaN  6.0
1  1.0   6.0   NaN  8.0  5.0
2  0.0  11.0  12.0  4.0  5.0
3  3.0   NaN   3.0  5.0  NaN
4  5.0   1.0   4.0  2.0  4.0

In [6]:
df.dropna(subset=['C'])

     A     B     C    D    E
0  5.0   2.0   3.0  NaN  6.0
2  0.0  11.0  12.0  4.0  5.0
3  3.0   NaN   3.0  5.0  NaN
4  5.0   1.0   4.0  2.0  4.0

補值則使用fillna函式即可，依照以下範例即可補上固定值0、平均數、眾數、中位數…

In [7]:
df.fillna(0)

     A     B     C    D    E
0  5.0   2.0   3.0  0.0  6.0
1  1.0   6.0   0.0  8.0  5.0
2  0.0  11.0  12.0  4.0  5.0
3  3.0   0.0   3.0  5.0  0.0
4  5.0   1.0   4.0  2.0  4.0

In [ ]:
df['B'] = df['B'].fillna(df['B'].mean())
df

     A     B     C    D    E
0  5.0   2.0   3.0  NaN  6.0
1  1.0   6.0   NaN  8.0  5.0
2  0.0  11.0  12.0  4.0  5.0
3  3.0   5.0   3.0  5.0  NaN
4  5.0   1.0   4.0  2.0  4.0

In [9]:
df['C'] = df['C'].fillna(df['C'].mode())
df

     A     B     C    D    E
0  5.0   2.0   3.0  NaN  6.0
1  1.0   6.0   NaN  8.0  5.0
2  0.0  11.0  12.0  4.0  5.0
3  3.0   5.0   3.0  5.0  NaN
4  5.0   1.0   4.0  2.0  4.0

In [10]:
df['D'] = df['D'].fillna(df['D'].median())
df

     A     B     C    D    E
0  5.0   2.0   3.0  4.5  6.0
1  1.0   6.0   NaN  8.0  5.0
2  0.0  11.0  12.0  4.0  5.0
3  3.0   5.0   3.0  5.0  NaN
4  5.0   1.0   4.0  2.0  4.0

In [11]:
df['E'] = df['E'].fillna(df['E'].min())
df

     A     B     C    D    E
0  5.0   2.0   3.0  4.5  6.0
1  1.0   6.0   NaN  8.0  5.0
2  0.0  11.0  12.0  4.0  5.0
3  3.0   5.0   3.0  5.0  4.0
4  5.0   1.0   4.0  2.0  4.0

XL, L, M, S, XS雖然是類別的屬性但因為有大小順序的關係，可以用10, 7 , 5, 3, 1來替換

In [12]:
df2 = pd.DataFrame(
    [['green','M', 10.1, 1],
     ['red', 'L', 13.5, 2],
     ['blue', 'XL', 15.3, 1]]
)
df2.columns = ['color', 'size', 'price', 'classlaber']
df2

   color size  price  classlaber
0  green    M   10.1           1
1    red    L   13.5           2
2   blue   XL   15.3           1

color跟size都是類別資料,
size是屬於有序的資料，我們只要稍微轉換為數值即可

In [13]:
df2['size'] = df2['size'].map({'XL':3,'L':2,'M':1})
df2

   color  size  price  classlaber
0  green     1   10.1           1
1    red     2   13.5           2
2   blue     3   15.3           1

color我們就用onehot-encoding的方法來處理

In [14]:
pd.get_dummies(df2['color'], dtype=float)

   blue  green  red
0   0.0    1.0  0.0
1   0.0    0.0  1.0
2   1.0    0.0  0.0

In [15]:
one_hot_encoding = pd.get_dummies(df2['color'],prefix='color',dtype =float)
df2

   color  size  price  classlaber
0  green     1   10.1           1
1    red     2   13.5           2
2   blue     3   15.3           1

In [16]:
pd.concat([one_hot_encoding, df2], axis=1)

   color_blue  color_green  color_red  color  size  price  classlaber
0         0.0          1.0        0.0  green     1   10.1           1
1         0.0          0.0        1.0    red     2   13.5           2
2         1.0          0.0        0.0   blue     3   15.3           1

特徵縮放是資料前處理的一個很重要的關鍵，只少有部分的Model不需要做特徵縮放，決策樹及其衍生算法：如隨機森林、極端梯度提升（XGBoost）。這些算法基於特徵的分割點進行決策，不依賴於特徵尺度。
在使用依賴距離的算法（如 K-means、SVM、線性回歸等）時，需要對數值型變數進行縮放。
需要特徵縮放主要是因為Model背後是用空間中的距離來做區分，假設某一個特徵過大，該Model的成本函數會被這個特徵所支配。
特徵縮放後能夠讓我們在做梯度下降時收斂更快。


最常見的Normalization為0~1區間縮放，經過Normalization之後資料的範圍會介在0~1之間，原本的最大值變為1，最小值變為0

In [17]:
from IPython.display import Math

In [18]:
Math(r'x^{(i)}_{norm}=\frac{x^{(i)}-x_{min}}{x_{max}-x_{min}}')

In [20]:
iris = datasets.load_iris()
x = pd.DataFrame(iris['data'], columns = iris['feature_names'])
y = pd.DataFrame(iris['target'], columns =['target_names'])
data = pd.concat([x,y], axis=1)
data.head(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target_names
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [22]:
data['sepal length (cm)'] = (data['sepal length (cm)'] - data['sepal length (cm)'].min())/\
                            (data['sepal length (cm)'].max() - data['sepal length (cm)'].min())
data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target_names
0,0.222222,3.5,1.4,0.2,0
1,0.166667,3.0,1.4,0.2,0
2,0.111111,3.2,1.3,0.2,0
3,0.083333,3.1,1.5,0.2,0
4,0.194444,3.6,1.4,0.2,0

經過Standardization資料的平均值會變為0, 標準差變為1，具體作法如下圖

In [23]:
Math(r'x^{(i)}_{std}=\frac{x^{(i)}-\mu_{x}}{\sigma_{x}}')

In [24]:
data['sepal width (cm)'] = (data['sepal width (cm)'] - data['sepal width (cm)'].mean())/\
                            (data['sepal width (cm)'].std())
data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target_names
0,0.222222,1.015602,1.4,0.2,0
1,0.166667,-0.131539,1.4,0.2,0
2,0.111111,0.327318,1.3,0.2,0
3,0.083333,0.097889,1.5,0.2,0
4,0.194444,1.245030,1.4,0.2,0